In [4]:
import re

In [1]:
url = "https://meet.google.com/iva-bwdm-hqg"

In [2]:
pattern = r"https?:[//]\S*"

In [3]:
url = "this is colab link : https://colab.research.google.com/drive/1KGxXJ3KV0DPFO90Jnh02UrGBB5TiNFQ7#scrollTo=_ogixQwr3gBm"

In [5]:
url_pattern = re.compile(pattern)
url_pattern.sub("",url)

'this is colab link : '

In [6]:
html_text = '''
<html>
<body>
    <header>
        <h1>Welcome to My Blog</h1>
    </header>
    <article>
        <h2>Post Title 1</h2>
        <p>Here is some content for my blog post. It could be about anything interesting or informative.</p>
        <p>Feel free to share your thoughts in the comments section below.</p>
    </article>
    <article>
        <h2>Post Title 2</h2>
        <p>This is another post with more content. Blogs are a great way to share information and ideas.</p>
        <p>Don't forget to subscribe for updates!</p>
    </article>
</body>
</html>

'''

In [7]:
pattern = r"<[^>]*>"

In [8]:
html_pattern = re.compile(pattern)


In [9]:
html_pattern.sub("",html_text)

"\n\n\n    \n        Welcome to My Blog\n    \n    \n        Post Title 1\n        Here is some content for my blog post. It could be about anything interesting or informative.\n        Feel free to share your thoughts in the comments section below.\n    \n    \n        Post Title 2\n        This is another post with more content. Blogs are a great way to share information and ideas.\n        Don't forget to subscribe for updates!\n    \n\n\n\n"

In [10]:
'''


        Welcome to My Blog


        Post Title 1
        Here is some content for my blog post. It could be about anything interesting or informative.
        Feel free to share your thoughts in the comments section below.


        Post Title 2
        This is another post with more content. Blogs are a great way to share information and ideas.
        Don't forget to subscribe for updates!



'''

"\n\n\n        Welcome to My Blog\n\n\n        Post Title 1\n        Here is some content for my blog post. It could be about anything interesting or informative.\n        Feel free to share your thoughts in the comments section below.\n\n\n        Post Title 2\n        This is another post with more content. Blogs are a great way to share information and ideas.\n        Don't forget to subscribe for updates!\n\n\n\n"

In [11]:
from bs4 import BeautifulSoup

In [13]:
BeautifulSoup(html_text,'lxml').text

FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

In [14]:
with open("Abbrivations.txt","r")as f:
    data = f.read()
    

In [15]:
data

'{\n    "$" : " dollar ",\n    "€" : " euro ",\n    "4ao" : "for adults only",\n    "a.m" : "before midday",\n    "a3" : "anytime anywhere anyplace",\n    "aamof" : "as a matter of fact",\n    "acct" : "account",\n    "adih" : "another day in hell",\n    "afaic" : "as far as i am concerned",\n    "afaict" : "as far as i can tell",\n    "afaik" : "as far as i know",\n    "afair" : "as far as i remember",\n    "afk" : "away from keyboard",\n    "app" : "application",\n    "approx" : "approximately",\n    "apps" : "applications",\n    "asap" : "as soon as possible",\n    "asl" : "age, sex, location",\n    "atk" : "at the keyboard",\n    "ave." : "avenue",\n    "aymm" : "are you my mother",\n    "ayor" : "at your own risk", \n    "b&b" : "bed and breakfast",\n    "b+b" : "bed and breakfast",\n    "b.c" : "before christ",\n    "b2b" : "business to business",\n    "b2c" : "business to customer",\n    "b4" : "before",\n    "b4n" : "bye for now",\n    "b@u" : "back at you",\n    "bae" : "befor

In [16]:
import ast

In [17]:
abbre_dict = ast.literal_eval(data)


In [18]:
abbre_dict

{'$': ' dollar ',
 '€': ' euro ',
 '4ao': 'for adults only',
 'a.m': 'before midday',
 'a3': 'anytime anywhere anyplace',
 'aamof': 'as a matter of fact',
 'acct': 'account',
 'adih': 'another day in hell',
 'afaic': 'as far as i am concerned',
 'afaict': 'as far as i can tell',
 'afaik': 'as far as i know',
 'afair': 'as far as i remember',
 'afk': 'away from keyboard',
 'app': 'application',
 'approx': 'approximately',
 'apps': 'applications',
 'asap': 'as soon as possible',
 'asl': 'age, sex, location',
 'atk': 'at the keyboard',
 'ave.': 'avenue',
 'aymm': 'are you my mother',
 'ayor': 'at your own risk',
 'b&b': 'bed and breakfast',
 'b+b': 'bed and breakfast',
 'b.c': 'before christ',
 'b2b': 'business to business',
 'b2c': 'business to customer',
 'b4': 'before',
 'b4n': 'bye for now',
 'b@u': 'back at you',
 'bae': 'before anyone else',
 'bak': 'back at keyboard',
 'bbbg': 'bye bye be good',
 'bbc': 'british broadcasting corporation',
 'bbias': 'be back in a second',
 'bbl': 'b

In [19]:
words = "complete this task asap"

word_list = []
for word in words.split():
    if word.lower() in abbre_dict.keys():
        word = abbre_dict[word.lower()]
        word_list.append(word)
    else:
        word_list.append(word)

" ".join(word_list)

'complete this task as soon as possible'

In [20]:
text = ["cat chased dog", "dog chased cat", "cat and dog playing"]

labels = [1,1,0]

In [21]:
import pandas as pd 

In [22]:
df = pd.DataFrame({"text" : text, "sentiment" : labels})
df

text  sentiment
0       cat chased dog          1
1       dog chased cat          1
2  cat and dog playing          0

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
count_vectorizer = CountVectorizer()

In [26]:
vectors = count_vectorizer.fit_transform(df["text"])
vectors

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [27]:
vectors[0].toarray()

array([[0, 1, 1, 1, 0]], dtype=int64)

In [28]:
count_vectorizer.vocabulary_

{'cat': 1, 'chased': 2, 'dog': 3, 'and': 0, 'playing': 4}

In [29]:
vectors[1].toarray()

array([[0, 1, 1, 1, 0]], dtype=int64)

In [30]:
vectors[2].toarray()

array([[1, 1, 0, 1, 1]], dtype=int64)